packages:
  - "apps/*"
  - "packages/*"
  - "infra/"

catalog:
  typescript: 5.8.3
  eslint: ^9.26.0
  prettier: ^3.5.3
  colyseus: ^0.16.4
  colyseus.js: ^0.16.16
  graphql: ^16.11.0
  "@apollo/server": ^4.12.0
  phaser: ^3.88.2
  react: ^18.3.1
  react-dom: ^18.3.1
  "@types/react": ^19.0.1
  "@types/react-dom": ^19.0.2
  "@types/node": ^22.14.1
  electron: ^36.2.0
  vite: ^6.3.5
  vitest: ^3.1.3
  "@vitest/coverage-v8": ^3.1.3
  "@vitejs/plugin-react": ^4.4.1
  tailwindcss: ^4.1.4
  postcss: ^8.5.3
  "@tailwindcss/postcss": ^4.1.4
  nanoid: ^5.1.5
  express: ^5.1.0
  "@types/express": ^5.0.1
  tsx: ^4.19.4
  mocha: ^11.2.2
  "@types/mocha": ^10.0.10
  c8: ^10.1.3
  nodemon: ^3.1.10
