packages:
  - "apps/*"
  - "packages/*"
  - "infra/"

catalog:
  typescript: 5.8.3
  zod: ^4.0.14
  dotenv: ^17.0.1
  eslint: ^9.26.0
  prettier: ^3.5.3
  colyseus: ^0.16.4
  colyseus.js: ^0.16.16
  prisma: ^6.8.2
  "@prisma/client": ^6.8.2
  graphql: ^16.11.0
  "@apollo/server": ^4.12.0
  "@apollo/client": ^3.13.8
  "@graphql-codegen/cli": ^5.0.6
  "@graphql-typed-document-node/core": ^3.2.0
  "@parcel/watcher": ^2.5.1
  phaser: 4.0.0-rc.4
  react: ^18.3.1
  react-dom: ^18.3.1
  react-router-dom: ^7.6.0
  "@supabase/supabase-js": ^2.49.4
  "@types/react": ^19.0.1
  "@types/react-dom": ^19.0.2
  "@types/node": ^22.14.1
  electron: ^36.2.0
  vite: ^6.3.5
  vitest: ^3.1.3
  "@vitest/coverage-v8": ^3.1.3
  "@vitejs/plugin-react": ^4.4.1
  "vite-plugin-dts": ^4.5.4
  "@rollup/plugin-typescript": ^12.1.2
  tailwindcss: ^4.1.4
  "@tailwindcss/vite": ^4.1.7
  "@tailwindcss/cli": ^4.1.4
  nanoid: ^5.1.5
  express: ^5.1.0
  "@types/express": ^5.0.1
  tsx: ^4.19.4
  mocha: ^11.2.2
  "@types/mocha": ^10.0.10
  c8: ^10.1.3
  nodemon: ^3.1.10
  validator: ^13.15.0
  "@types/validator": ^13.15.0
  jsonwebtoken: ^9.0.2
  "@types/jsonwebtoken": ^9.0.9
