packages:
  - "apps/*"
  - "packages/*"
  - "infra/"

catalog:
  eslint: ^9.26.0
  prettier: ^3.5.3
  react: ^18.3.1
  react-dom: ^18.3.1
  vitest: ^3.1.3
  "@vitest/coverage-v8": ^3.1.3
  typescript: 5.5.4
