packages:
  - "apps/*"
  - "packages/*"

catalog:
  typescript: 5.9.3
  zod: ^4.0.14
  dotenv: ^17.0.1
  eslint: ^9.26.0
  prettier: ^3.5.3
  colyseus: ^0.16.4
  colyseus.js: ^0.16.16
  prisma: ^7.2.0
  "@prisma/client": ^7.2.0
  "@prisma/adapter-pg": ^7.2.0
  graphql: ^16.11.0
  "@apollo/server": ^5.2.0
  "@apollo/client": ^4.0.11
  rxjs: ^7.8.2
  "@graphql-codegen/cli": ^6.1.0
  "@graphql-typed-document-node/core": ^3.2.0
  "@parcel/watcher": ^2.5.1
  phaser: 4.0.0-rc.6
  three: ^0.182.0
  "@types/three": ^0.182.0
  "@react-three/fiber": ^8.18.0
  "@react-three/drei": ^9.122.0
  react: ^18.3.1
  react-dom: ^18.3.1
  react-router-dom: ^7.6.0
  "@supabase/supabase-js": ^2.49.4
  "@types/react": ^18.3.1
  "@types/react-dom": ^18.3.7
  "@types/node": ^24.10.4
  electron: ^39.2.7
  vite: ^7.3.0
  vitest: ^4.0.16
  "@vitest/coverage-v8": ^4.0.16
  "@vitejs/plugin-react": ^5.1.2
  "vite-plugin-dts": ^4.5.4
  "@rollup/plugin-typescript": ^12.1.2
  tailwindcss: ^4.1.4
  "@tailwindcss/vite": ^4.1.7
  "@tailwindcss/cli": ^4.1.4
  nanoid: ^5.1.5
  express: ^5.1.0
  "@types/express": ^5.0.1
  tsx: ^4.19.4
  mocha: ^11.2.2
  "@types/mocha": ^10.0.10
  c8: ^10.1.3
  nodemon: ^3.1.10
  validator: ^13.15.0
  "@types/validator": ^13.15.0
  jsonwebtoken: ^9.0.2
  "@types/jsonwebtoken": ^9.0.9
