services:
  postgres-db:
    image: postgres:17.5
    container_name: game_postgres_db
    restart: always
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: game_db
    ports:
      - "5432:5432"
